spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/doniaCh
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs  # Correction ici : "jwk-set-uri" au lieu de "jwt-se-uri"

server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: donia-rest-api
      principle-attribute: preferred_username
